### ISSUE TITLE
"No valid points" when running demo on example data 

### ISSUE THREAD

**Issue by ftasse** [zju3dv/NeuralRecon#6] opened 2021-05-11 17:29 UTC
Hi Team, thanks for sharing this outstanding piece of work. When trying to run demo.py on the example data provided  in DEMO.md I come across the error message below after following all the steps. Any idea why reconstruction is failing? I get the same error when I run it on my own captured ARKit data.

2021-05-10 19:51:55.606 | INFO     | __main__:<module>:35 - Found SyncedPoses.txt, skipping data pre-processing...
2021-05-10 19:51:55.606 | INFO     | __main__:<module>:37 - Running NeuralRecon...
2021-05-10 19:51:55.613 | INFO     | __main__:<module>:50 - Initializing the model on GPU...
2021-05-10 19:51:58.977 | INFO     | __main__:<module>:58 - Resuming from ./checkpoints/model_000047.ckpt
2021-05-10 19:51:59.299 | INFO     | __main__:<module>:64 - Start inference..
  0%|                                                   | 0/111 [00:00<?, ?it/s]2021-05-10 19:52:00.083 | WARNING  | models.neucon_network:forward:184 - no valid points: scale 1
  0%|                                                   | 0/111 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "demo.py", line 78, in <module>
    save_mesh_scene(outputs, sample, epoch_idx)
  File "NeuralRecon/utils.py", line 320, in __call__
    self.tsdf_volume.append(outputs['scene_tsdf'])
KeyError: 'scene_tsdf'

**Comment by Sandell0** [comment] 2021-05-12 08:44
It is possible to get images and intermediate meshes by adding a condition before save_mesh_scene.          
```
	if "scene_tsdf" in outputs:
		save_mesh_scene(outputs, sample, epoch_idx)
```
However, the result is completely unrecognizable.

**Comment by JiamingSuen** [comment] 2021-05-12 13:32
The issue should be fixed by the latest commit. You can pull the latest version and try again. Sorry for the caused trouble.

To provide some details, the X-Y plane in the ARKit coordinates should be moved downwards a little to meet the training settings on ScanNet.

**Comment by EddieKro** [comment] 2021-05-12 15:34
> The issue should be fixed by the latest commit. You can pull the latest version and try again. Sorry for the caused trouble.
> 
> To provide some details, the X-Y plane in the ARKit coordinates should be moved downwards a little to meet the training settings on ScanNet.

Hello! Latest commit fixed an error, but the results are still unrecognizable.
Should results look like this?  [https://drive.google.com/file/d/1g-woNtSl8duVeV2IETtxlDB-PjVmYo4a/view?usp=sharing](url)

**Comment by Sandell0** [comment] 2021-05-12 15:41
I reloaded demo data, and it worked fine after that.

**Comment by JiamingSuen** [comment] 2021-05-12 15:43
> > The issue should be fixed by the latest commit. You can pull the latest version and try again. Sorry for the caused trouble.
> > To provide some details, the X-Y plane in the ARKit coordinates should be moved downwards a little to meet the training settings on ScanNet.
> 
> Hello! Latest commit fixed an error, but the results are still unrecognizable.
> Should results on demo data look like this? [https://drive.google.com/file/d/1g-woNtSl8duVeV2IETtxlDB-PjVmYo4a/view?usp=sharing](url)

It appears that the overall shape is correct and the problem is on the shading mode in MeshLab. You can try to use this shading configuration in MeshLab:
![image](https://user-images.githubusercontent.com/8616975/118004156-cc9b2100-b37b-11eb-8fb0-0bca49657bc4.png)

The released demo data is the data used in the [header video](https://zju3dv.github.io/neuralrecon/#header_vid) on the project page. The [corresponding mesh](https://sketchfab.com/3d-models/neuralrecon-reconstruction-on-b5-scene2-f0599e862efc4d178d58622963bd9183) is also hosted on Skechfab.

**Comment by EddieKro** [comment] 2021-05-12 16:10
> > > The issue should be fixed by the latest commit. You can pull the latest version and try again. Sorry for the caused trouble.
> > > To provide some details, the X-Y plane in the ARKit coordinates should be moved downwards a little to meet the training settings on ScanNet.
> > 
> > 
> > Hello! Latest commit fixed an error, but the results are still unrecognizable.
> > Should results on demo data look like this? [https://drive.google.com/file/d/1g-woNtSl8duVeV2IETtxlDB-PjVmYo4a/view?usp=sharing](url)
> 
> It appears that the overall shape is correct and the problem is on the shading mode in MeshLab. You can try to use this shading configuration in MeshLab:
> ![image](https://user-images.githubusercontent.com/8616975/118004156-cc9b2100-b37b-11eb-8fb0-0bca49657bc4.png)
> 
> The released demo data is the data used in the [header video](https://zju3dv.github.io/neuralrecon/#header_vid) on the project page. The [corresponding mesh](https://sketchfab.com/3d-models/neuralrecon-reconstruction-on-b5-scene2-f0599e862efc4d178d58622963bd9183) is also hosted on Skechfab.

Turns out I loaded all the generated meshes at once. Now everything's fine, thank you for the quick response!

**Comment by JiamingSuen** [comment] 2021-05-13 06:45
@ftasse Please confirm that you have also been able to run the demo with the latest commit, thanks!

**Comment by ftasse** [comment] 2021-05-13 16:55
@JiamingSuen  Thank you for looking into this super fast. It works great, and I was able to test it on my own captured data as well. Awesome work!

**Comment by JiamingSuen** [comment] 2021-05-13 18:08
> @JiamingSuen Thank you for looking into this super fast. It works great, and I was able to test it on my own captured data as well. Awesome work!

Thanks for your reply (and also for raising this issue)! Glad that you like our work!

**Closed by JiamingSuen** 2021-05-13 18:08 UTC

**Comment by linzhenyuyuchen** [comment] 2022-08-01 08:21
> The issue should be fixed by the latest commit. You can pull the latest version and try again. Sorry for the caused trouble.
> 
> To provide some details, the X-Y plane in the ARKit coordinates should be moved downwards a little to meet the training settings on ScanNet.
> 
> UPDATE: Please notice that the data preprocessing needs to be run again after pulling the latest code, which can be achieved by simply deleting `SyncedPoses.txt` in the data folder.

Hello, thank you for your great work. 
Could you explain that why the ARKit coordinates should be moved downwards a little.
BTW, when we run NeuralRecon on our own data, it occurred `no valid points: scale 1/2` like this issue.
Whether should we pre-process our own data to meet `some kind of `  training settings on ScanNet ?
Could you provide the training setting in detail?
